name: Docker Image VaMEx3 Fieldtest

on:
  workflow_dispatch: # Manually triggered workflow
    inputs:
      version:
        description: 'Version of the Docker image'
        required: true
        default: '1.0.0'
      image_name:
        description: 'Name of the Docker image'
        required: true
        default: 'mrg_slam_jazzy'

jobs:
  # build_and_push_ubuntu_22:
  #   runs-on: ubuntu-22.04

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to DockerHub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #       password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  #   - name: Build and push
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: .
  #       file: ./docker/humble_remote/Dockerfile
  #       platforms: linux/amd64, linux/arm64
  #       push: true
  #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mrg_slam_humble:latest,${{ secrets.DOCKER_HUB_USERNAME }}/mrg_slam_humble:${{ github.event.inputs.version }}

  build_and_push_ubuntu_24:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        ref: vamex3_fieldtest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Gitlab Container Registry
      uses: docker/login-action@v2
      with:
        registry: gitlab.informatik.uni-bremen.de:5005
        username: ${{ secrets.GITLAB_BREMEN_USERNAME }}
        password: ${{ secrets.GITLAB_BREMEN_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/jazzy_remote/Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: gitlab.informatik.uni-bremen.de:5005/vamex/container-repository/${{ github.event.inputs.image_name }}:latest,gitlab.informatik.uni-bremen.de:5005/vamex/container-repository/${{ github.event.inputs.image_name }}:${{ github.event.inputs.version }}